# Generated by Django 5.1.3 on 2024-12-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_orders', '0007_rename_create_at_order_created_at_alter_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
