# Generated by Django 5.1.3 on 2024-12-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shope', '0002_alter_category_table_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
    ]
