# Generated by Django 5.1.3 on 2024-12-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shope', '0003_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/'),
        ),
    ]
