# Generated by Django 5.1.3 on 2024-12-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0004_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Drink', 'Drink'), ('Smoothie', 'Smoothie')], default='Breakfast', max_length=30),
        ),
    ]
