# Generated by Django 5.1.3 on 2024-12-19 11:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shope', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('postal_code', models.CharField(default='00000', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_cart_items', to='shope.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_cart_items', to='shope.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=20)),
                ('order_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_order_address', to='orders.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_items', to='shope.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProceedToCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Apple Pay', 'Apple Pay')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=20)),
                ('payment_id', models.CharField(max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('shipping_method', models.CharField(max_length=100, null=True)),
                ('tracking_number', models.CharField(max_length=100, null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('delivery_time', models.TimeField(null=True)),
                ('delivery_note', models.TextField(null=True)),
                ('cancellation_reason', models.CharField(max_length=200, null=True)),
                ('cancellation_note', models.TextField(null=True)),
                ('cancellation_date', models.DateField(null=True)),
                ('cancellation_time', models.TimeField(null=True)),
                ('cancellation_payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Apple Pay', 'Apple Pay')], max_length=20, null=True)),
                ('cancellation_payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=20, null=True)),
                ('cancellation_payment_id', models.CharField(max_length=100, null=True)),
                ('cancellation_total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cancellation_shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('cancellation_tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('cancellation_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('cancellation_shipping_method', models.CharField(max_length=100, null=True)),
                ('cancellation_tracking_number', models.CharField(max_length=100, null=True)),
                ('cancellation_delivery_date', models.DateField(null=True)),
                ('cancellation_delivery_time', models.TimeField(null=True)),
                ('cancellation_delivery_note', models.TextField(null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_proceed_to_checkout', to='shope.cart')),
                ('order_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_proceed_to_checkout_order_address', to='orders.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_proceed_to_checkout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Checkouts',
            },
        ),
    ]
