# Generated by Django 5.1.3 on 2024-12-24 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
