# Generated by Django 5.1.3 on 2024-12-24 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.address'),
        ),
    ]
